name: kiss_auth
description: A modular authentication and authorization interface for Dart applications.
version: 0.1.0
repository: https://github.com/WAMF/kiss_auth

environment:
  sdk: ^3.8.1

# Add regular dependencies here.
dependencies:
  dart_jsonwebtoken: ^3.2.0
  meta: ^1.8.0
  very_good_analysis: ^9.0.0

dev_dependencies:
  lints: ^5.0.0
  test: ^1.24.0
