include: package:very_good_analysis/analysis_options.yaml
analyzer:
  plugins:
    - custom_lint
  exclude:
    - '**.g.dart'
    - '**.gen.dart'
    - '**.freezed.dart'
    - '**.generated.dart'
    - '**.tailor.dart'
    - 'lib/l10n/**'
linter:
  rules:
    one_member_abstracts: false
    public_member_api_docs: false
    sort_pub_dependencies: false
    lines_longer_than_80_chars: false
    avoid_print: false
    